export const FETCH_ACTOR_DETAIL_REQUEST = "FETCH_ACTOR_DETAIL_REQUEST";
export const FETCH_ACTOR_DETAIL_SUCCESS = "FETCH_ACTOR_DETAIL_SUCCESS";
export const FETCH_ACTOR_DETAIL_FAIL = "FETCH_ACTOR_DETAIL_FAIL";
