export const FETCH_DIRECTOR_DETAIL_REQUEST = "FETCH_DIRECTOR_DETAIL_REQUEST";
export const FETCH_DIRECTOR_DETAIL_SUCCESS = "FETCH_DIRECTOR_DETAIL_SUCCESS";
export const FETCH_DIRECTOR_DETAIL_FAIL = "FETCH_DIRECTOR_DETAIL_FAIL";
