export const FETCH_TRENDING_REQUEST = "FETCH_TRENDING_REQUEST";
export const FETCH_TRENDING_SUCCESS = "FETCH_TRENDING_SUCCESS";
export const FETCH_TRENDING_FAIL = "FETCH_TRENDING_FAIL";

export const FETCH_FILM_DETAIL_REQUEST = "FETCH_FILM_DETAIL_REQUEST";
export const FETCH_FILM_DETAIL_SUCCESS = "FETCH_FILM_DETAIL_SUCCESS";
export const FETCH_FILM_DETAIL_FAIL = "FETCH_FILM_DETAIL_FAIL";

export const SEARCH_FILMS_REQUEST = "SEARCH_FILMS_REQUEST";
export const SEARCH_FILMS_SUCCESS = "SEARCH_FILMS_SUCCESS";
export const SEARCH_FILMS_FAIL = "SEARCH_FILMS_FAIL";

export const FETCH_FAVORITE_FILMS_REQUEST = "FETCH_FAVORITE_FILMS_REQUEST";
export const FETCH_FAVORITE_FILMS_SUCCESS = "FETCH_FAVORITE_FILMS_SUCCESS";
export const FETCH_FAVORITE_FILMS_FAIL = "FETCH_FAVORITE_FILMS_FAIL";
