export const NEWLIST_SEARCH_FILMS_REQUEST = "NEWLIST_SEARCH_FILMS_REQUEST";
export const NEWLIST_SEARCH_FILMS_SUCCESS = "NEWLIST_SEARCH_FILMS_SUCCESS";
export const NEWLIST_SEARCH_FILMS_FAIL = "NEWLIST_SEARCH_FILMS_FAIL";

export const NEWLIST_ADD_FILM = "NEWLIST_ADD_FILM";
export const NEWLIST_REMOVE_FILM = "NEWLIST_REMOVE_FILM";
