export const NEWLIST_SEARCH_FILMS_REQUEST = "NEWLIST_SEARCH_FILMS_REQUEST";
export const NEWLIST_SEARCH_FILMS_SUCCESS = "NEWLIST_SEARCH_FILMS_SUCCESS";
export const NEWLIST_SEARCH_FILMS_FAIL = "NEWLIST_SEARCH_FILMS_FAIL";

export const NEWLIST_ADD_FILM = "NEWLIST_ADD_FILM";
export const NEWLIST_REMOVE_FILM = "NEWLIST_REMOVE_FILM";

export const LIST_DETAILS_REQUEST = "LIST_DETAILS_REQUEST";
export const LIST_DETAILS_SUCCESS = "LIST_DETAILS_SUCCESS";
export const LIST_DETAILS_FAIL = "LIST_DETAILS_FAIL";

export const FEATURED_LISTS_REQUEST = "FEATURED_LISTS_REQUEST";
export const FEATURED_LISTS_SUCCESS = "FEATURED_LISTS_SUCCESS";
export const FEATURED_LISTS_FAIL = "FEATURED_LISTS_FAIL";
