export const DIARY_REQUEST = "DIARY_REQUEST";
export const DIARY_SUCCESS = "DIARY_SUCCESS";
export const DIARY_FAIL = "DIARY_FAIL";

export const WATCHLIST_REQUEST = "WATCHLIST_REQUEST";
export const WATCHLIST_SUCCESS = "WATCHLIST_SUCCESS";
export const WATCHLIST_FAIL = "WATCHLIST_FAIL";
