export const RECENT_REVIEWS_REQUEST = "RECENT_REVIEWS_REQUEST";
export const RECENT_REVIEWS_SUCCESS = "RECENT_REVIEWS_SUCCESS";
export const RECENT_REVIEWS_FAIL = "RECENT_REVIEWS_FAIL";

export const POPULAR_REVIEWS_REQUEST = "POPULAR_REVIEWS_REQUEST";
export const POPULAR_REVIEWS_SUCCESS = "POPULAR_REVIEWS_SUCCESS";
export const POPULAR_REVIEWS_FAIL = "POPULAR_REVIEWS_FAIL";

export const USER_REVIEWS_REQUEST = "USER_REVIEWS_REQUEST";
export const USER_REVIEWS_SUCCESS = "USER_REVIEWS_SUCCESS";
export const USER_REVIEWS_FAIL = "USER_REVIEWS_FAIL";
